# Generated by Django 6.0.7 on 2026-07-31 03:50

import django.db.models.deletion
from django.db import migrations, models


def delete_all_issues(apps, schema_editor):
    Issue = apps.get_model('issue', 'Issue')
    Issue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='affected_application',
        ),
        migrations.AddField(
            model_name='issue',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issue.application'),
        ),
        migrations.RunPython(delete_all_issues),
        migrations.AlterField(
            model_name='issue',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issue.application'),
        ),
    ]
