# Generated by Django 6.0.7 on 2026-07-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_application_remove_issue_affected_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
    ]
